VERIFICATION_SUBJECT = "%(desription)s Verification Code"

# FIXME: Is "ignore this message" actually good advice?
VERIFICATION_BODY_LONG = """\
%(description)s: %(vcode)s is your verification code.

This code expires in %(timeout_minutes)s minutes. Don't share it with
anyone. If you were not expecting this verification code, please
ignore this message."""

# This is deliberately chosen to be similar to SMS messages sent by
# popular online service providers. We hope users are familiar with
# the phrasing and telco spam filters likey to let them through.
VERIFICATION_BODY_SHORT = """\
 %(description)s: %(vcode)s is your verification code.\
 It expires in %(timeout_minutes)s minutes.\
 Don't share this code with anyone."""


OUTER_EMAIL_TEMPLATE = """\
To: %(to)s
From: %(from)s
Subject: %(subject)s
Date: %(date)s
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
User-Agent: Passcrow Server

%(message)s

-- 
Generated by Passcrow, an open community system for password recovery.
Read more here: %(about_url)s
"""
